require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/licencia", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Licencium. As you add validations to Licencium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Licencium.create! valid_attributes
      get licencia_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      licencium = Licencium.create! valid_attributes
      get licencium_url(licencium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_licencium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      licencium = Licencium.create! valid_attributes
      get edit_licencium_url(licencium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Licencium" do
        expect {
          post licencia_url, params: { licencium: valid_attributes }
        }.to change(Licencium, :count).by(1)
      end

      it "redirects to the created licencium" do
        post licencia_url, params: { licencium: valid_attributes }
        expect(response).to redirect_to(licencium_url(Licencium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Licencium" do
        expect {
          post licencia_url, params: { licencium: invalid_attributes }
        }.to change(Licencium, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post licencia_url, params: { licencium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested licencium" do
        licencium = Licencium.create! valid_attributes
        patch licencium_url(licencium), params: { licencium: new_attributes }
        licencium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the licencium" do
        licencium = Licencium.create! valid_attributes
        patch licencium_url(licencium), params: { licencium: new_attributes }
        licencium.reload
        expect(response).to redirect_to(licencium_url(licencium))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        licencium = Licencium.create! valid_attributes
        patch licencium_url(licencium), params: { licencium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested licencium" do
      licencium = Licencium.create! valid_attributes
      expect {
        delete licencium_url(licencium)
      }.to change(Licencium, :count).by(-1)
    end

    it "redirects to the licencia list" do
      licencium = Licencium.create! valid_attributes
      delete licencium_url(licencium)
      expect(response).to redirect_to(licencia_url)
    end
  end
end
