require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/physicals", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Physical. As you add validations to Physical, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Physical.create! valid_attributes
      get physicals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      physical = Physical.create! valid_attributes
      get physical_url(physical)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_physical_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      physical = Physical.create! valid_attributes
      get edit_physical_url(physical)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Physical" do
        expect {
          post physicals_url, params: { physical: valid_attributes }
        }.to change(Physical, :count).by(1)
      end

      it "redirects to the created physical" do
        post physicals_url, params: { physical: valid_attributes }
        expect(response).to redirect_to(physical_url(Physical.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Physical" do
        expect {
          post physicals_url, params: { physical: invalid_attributes }
        }.to change(Physical, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post physicals_url, params: { physical: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested physical" do
        physical = Physical.create! valid_attributes
        patch physical_url(physical), params: { physical: new_attributes }
        physical.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the physical" do
        physical = Physical.create! valid_attributes
        patch physical_url(physical), params: { physical: new_attributes }
        physical.reload
        expect(response).to redirect_to(physical_url(physical))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        physical = Physical.create! valid_attributes
        patch physical_url(physical), params: { physical: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested physical" do
      physical = Physical.create! valid_attributes
      expect {
        delete physical_url(physical)
      }.to change(Physical, :count).by(-1)
    end

    it "redirects to the physicals list" do
      physical = Physical.create! valid_attributes
      delete physical_url(physical)
      expect(response).to redirect_to(physicals_url)
    end
  end
end
